### **Multiple Linear Regression (다중 선형 회귀)**

#### **원-핫 인코딩**

In [1]:
import pandas as pd

In [2]:
dataset = pd.read_csv('MultipleLinearRegressionData.csv')
X = dataset.iloc[:, :-1].values
Y = dataset.iloc[:,-1].values

In [3]:
X

array([[0.5, 3, 'Home'],
       [1.2, 4, 'Library'],
       [1.8, 2, 'Cafe'],
       [2.4, 0, 'Cafe'],
       [2.6, 2, 'Home'],
       [3.2, 0, 'Home'],
       [3.9, 0, 'Library'],
       [4.4, 0, 'Library'],
       [4.5, 5, 'Home'],
       [5.0, 1, 'Cafe'],
       [5.3, 2, 'Cafe'],
       [5.8, 0, 'Cafe'],
       [6.0, 3, 'Library'],
       [6.1, 1, 'Cafe'],
       [6.2, 1, 'Library'],
       [6.9, 4, 'Home'],
       [7.2, 2, 'Cafe'],
       [8.4, 1, 'Home'],
       [8.6, 1, 'Library'],
       [10.0, 0, 'Library']], dtype=object)

In [4]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(drop='first'), [2])], remainder='passthrough')
X = ct.fit_transform(X)
X

# 1, 0 = Home
# 0, 1 = Library
# 0, 0 = Cafe

array([[1.0, 0.0, 0.5, 3],
       [0.0, 1.0, 1.2, 4],
       [0.0, 0.0, 1.8, 2],
       [0.0, 0.0, 2.4, 0],
       [1.0, 0.0, 2.6, 2],
       [1.0, 0.0, 3.2, 0],
       [0.0, 1.0, 3.9, 0],
       [0.0, 1.0, 4.4, 0],
       [1.0, 0.0, 4.5, 5],
       [0.0, 0.0, 5.0, 1],
       [0.0, 0.0, 5.3, 2],
       [0.0, 0.0, 5.8, 0],
       [0.0, 1.0, 6.0, 3],
       [0.0, 0.0, 6.1, 1],
       [0.0, 1.0, 6.2, 1],
       [1.0, 0.0, 6.9, 4],
       [0.0, 0.0, 7.2, 2],
       [1.0, 0.0, 8.4, 1],
       [0.0, 1.0, 8.6, 1],
       [0.0, 1.0, 10.0, 0]], dtype=object)

### **데이터 세트 분리**

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

### **학습 (다중 선형 회귀)**

In [7]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(X_train, Y_train)

LinearRegression()

### **예측 값과 실제 값 비교 (테스트 세트)**

In [8]:
Y_pred = reg.predict(X_test)
Y_pred

array([ 92.15457859,  10.23753043, 108.36245302,  38.14675204])

In [9]:
Y_test

array([ 90,   8, 100,  38], dtype=int64)

In [10]:
reg.coef_

array([-5.82712824, -1.04450647, 10.40419528, -1.64200104])

In [11]:
reg.intercept_

5.365006706544783

### **모델 평가**

In [12]:
reg.score(X_train,Y_train) # 훈련 세트

0.9623352565265527

In [13]:
reg.score(X_test, Y_test)  # 테스트 세트

0.9859956178877447

### **다양한 평가 지표 (회귀 모델)**

*1. MAE (Mean Absolute Error) : (실제 값과 예측 값) 차이의 절대값*\
*2. MSE (Mean Squared Errod) : 차이의 제곱*\
*3. RMSE (Root Mean Squared Error) : 차이의 제곱에 루트*\
*4. R2 : 결정 계수*

*>> R2는 1에 가까울수록, 나머지는 0에 가까울수록 좋음*

In [14]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(Y_test, Y_pred) # 실제 값, 예측 값 # MAE

3.2253285188287943

In [15]:
from sklearn.metrics import mean_squared_error
mean_squared_error(Y_test, Y_pred) # MSE

19.900226981514848

In [16]:
from sklearn.metrics import mean_squared_error
mean_squared_error(Y_test, Y_pred, squared=False)  # RMSE

4.460967045553559

In [17]:
from sklearn.metrics import r2_score
r2_score(Y_test,Y_pred) # R2

0.9859956178877447